# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14ffff43d9cf9e68d0658c9e852d472d89f013c706492cc763c025eca2d30ea9198113081b34d661ee773f713ccbf290ea1b3067421c6164aff0119159fcc04c

test:
  secret_key_base: 44d51a6ed661bb24927a2d41ee9a1ef46b663079ed881d476b546c4b3d85fe6d7e136d9df61f966682294c3bb3930adac2e7fd9146edaa7ec7e175e7a03ed309

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
